### ISSUE TITLE
Should we use graphql?

### ISSUE THREAD

**Issue by MikailBag** [jjs-dev/jjs#276]
I don't think I'm able to implement proper interaction with DB.
Criteria:
 - One API query turns into one DB query
 - All DB details are hidden in `src/db`

Possible solutions:
  - Someone maintains frontend
  - API is switched to REST

**Comment by pavel-the-best** [comment]
Yes, I think we should, because GraphQL allows clients not to download excessive data.
And I also think that we should "hire" Rust API developer, who wants to support open-source (for example, in technocup chat).

**Comment by MikailBag** [comment]
Network usage can be optimized in REST API too - for example, user can specify in some header filter: e.g. ["Run.id", "Run.status.kind", "Contest.phase"] (all fields, not specified in filter are deleted).
Also please note, that REST API can be comfortable for user too, for example with Swagger (it can generate API client).
