### ISSUE TITLE
C toolchain does not compile

### ISSUE THREAD

**Issue by sleirsgoevy** [jjs-dev/jjs#281]
C compiler from the C toolchain fails even for perfectly valid C code. The same C code runs fine using the C++ toolchain.

**Comment by MikailBag** [comment]
Quickfix: use the same hack as in https://github.com/jjs-dev/jjs/blob/master/toolchains/g%2B%2B/invoke-conf.yaml#L5

**Comment by pavel-the-best** [comment]
I'll apply this hack to C and Go in PR
