### ISSUE TITLE
No TLS by default

### ISSUE THREAD

**Issue by pavel-the-best** [jjs-dev/jjs#285]
There is no possibility for JJS administrators to enable TLS in one-click way. They need to install & configure nginx.

**Comment by MikailBag** [comment]
Fixed in #288

**Comment by pavel-the-best** [comment]
@MikailBag Any documentation on how to use that?

**Comment by MikailBag** [comment]
@pavel-the-best Unfortunately, we do not have beautiful frontend config docs.
